openapi: "3.0.0"
info:
  version: 1.0.0
  title: HomeNet
  description: |
    listings of properties for sale
  license:
    name: MIT
servers:
- url: http://localhost:3000
paths:
  /listings:
    get:
      summary: List listings
      operationId: listListings
      tags:
        - listings
      responses:
        '200':
          description: Array of listings
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/ResponseListings"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a Listing
      operationId: createListing
      tags:
      - listings
      requestBody:
        description: the listing to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Listing'
      responses:
        '201':
          description: The created listing
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/ResponseListing"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /listings/{listingId}:
    get:
      summary: get a listing
      operationId: getListing
      tags:
      - listings
      parameters:
      - name: listingId
        in: path
        description: listing by id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: the listing
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/ResponseListings"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    
    patch:
      summary: Update a Listing
      operationId: patchListing
      tags:
        - listings
      parameters:
      - name: listingId
        in: path
        description: listing id
        required: true
        schema:
          type: string
      requestBody:
        description: the listing to change
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Listing'
      responses:
        '200':
          description: The updated post
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/ResponseListing"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
                
    delete:
      summary: Delete a Listing
      operationId: deleteListing
      tags:
        - listings
      parameters:
      - name: listingId
        in: path
        description: listing id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: The deleted listing
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/ResponseListing"
        '204':
          description: No change (nothing was deleted)
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    
components:
  schemas:
    Listing:
      properties:
        listing:
          properties:
            kommun:
              type: string
            gata:
              type: string
            bostadstyp:
              type: string
            pris:
              type: string
            månadskostnad:
             type: string
            budning:
              type: boolean
            kordinater:
              properties:
                lat:
                  type: number
                long:
                  type: number
    ResponseListing:
      allOf:
      - $ref: "#/components/schemas/Listing"
      - properties:
          id:
            type: integer
          _id:
            type: string
            format: uuid
    ResponseListings:
      type: array
      items:
        $ref: "#/components/schemas/ResponseListing"
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
